version: "3"
services:
  vscode-container:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/node/.ssh
    env_file: devcontainer.env
  attendance-list-mongodb:
    image: mongo:6-jammy
    restart: always
    hostname: attendance-list-mongodb-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=attendance-list
    ports:
      - "27017:27017"
    volumes:
      - attendance-list-mongodb:/data/db
volumes:
  attendance-list-mongodb:
    driver: local
